### ISSUE TITLE
Storage api client exception as user error

### ISSUE THREAD

**Issue by ujovlado** [keboola/wr-storage#19] opened 2019-01-09 15:47 UTC
Current:
```
{"class":"Keboola\\StorageApi\\ClientException","message":"Row 476438545 not found","code":404,
```
It will end with app error.

Expected:
user error

**Comment by odinuv** [comment] 2019-01-09 15:54
duplicate of https://github.com/keboola/docker-bundle/issues/315

**Closed by odinuv** 2019-01-09 15:54 UTC
